version: 2.0
jobs:
  build:
    branches:
      only: [v1.0.0]
    docker:
      - image: ../.tests/DockerfileUbuntu
    steps:
      - run:
          name: Setup
          command: |
            redis-server &
            cd /tmp/hyperglass
            poetry run hyperglass setup -d
            poetry run hyperglass build-ui
      - run:
          name: Set listen_address
          command: |
            echo "listen_address: 127.0.0.1" >> /root/hyperglass/hyperglass.yaml
      - run:
          name: Start
          command: |
            poetry run hyperglass start &> /var/log/hyperglassci.log &
            sleep 10
      - run:
          name: Test
          command: |
            curl -s -o /dev/null -w "%{http_code}" http://localhost:8001
